In [1]:
import torch

# Simplified Self-Attention

In [2]:
inputs = torch.tensor(
    [[0.43, 0.15, 0.89],
     [0.55, 0.87, 0.66],
     [0.57, 0.85, 0.64],
     [0.22, 0.58, 0.22],
     [0.77, 0.25, 0.10],
     [0.05, 0.80, 0.55]]
)

inputs.shape

torch.Size([6, 3])

In [3]:
query = inputs[1]

attn_scores_2 = torch.empty(inputs.shape[0])
print(f"attn_scores_2: {attn_scores_2} ")

for i, x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(x_i, query)
print(attn_scores_2)

attn_scores_2: tensor([0., 0., 0., 0., 0., 0.]) 
tensor([0.9544, 1.4950, 1.4754, 0.7708, 0.7070, 1.0865])


In [4]:
def softmax_naive(x):
    return torch.exp(x) / torch.exp(x).sum(dim=0)

attn_weights_2_naive = softmax_naive(attn_scores_2)
print("Attention weights:", attn_weights_2_naive)
print("Sum:", attn_weights_2_naive.sum())

Attention weights: tensor([0.1398, 0.2400, 0.2353, 0.1163, 0.1091, 0.1595])
Sum: tensor(1.0000)


In [5]:
attn_weights_2 = torch.softmax(attn_scores_2, dim=0)
print("Attention weights:", attn_weights_2)
print("Sum:", attn_weights_2.sum())

Attention weights: tensor([0.1398, 0.2400, 0.2353, 0.1163, 0.1091, 0.1595])
Sum: tensor(1.0000)


In [6]:
x1 = torch.tensor([0.4, 0.1, 0.8])
x_1 = torch.tensor([0.43, 0.15, 0.89])
x2 = torch.tensor([0.5, 0.8, 0.6])
x_2 = torch.tensor([0.55, 0.87, 0.66])

print(x1)
print(x2)
print(torch.dot(x1, x2))
print(x1@x2)


print(x_1)
print(x_2)
print(x_1@x_2)


tensor([0.4000, 0.1000, 0.8000])
tensor([0.5000, 0.8000, 0.6000])
tensor(0.7600)
tensor(0.7600)
tensor([0.4300, 0.1500, 0.8900])
tensor([0.5500, 0.8700, 0.6600])
tensor(0.9544)


In [7]:
query = inputs[1]
context_vec_2 = torch.zeros(query.shape)
for i, x_i in enumerate(inputs):
    context_vec_2 += attn_weights_2[i] * x_i
print(context_vec_2)

tensor([0.4438, 0.6521, 0.5576])


In [8]:
# simplified self-attention

attn_scores = inputs @ inputs.T
attn_weights = torch.softmax(attn_scores, dim=-1)
all_context_vecs = attn_weights @ inputs

print(attn_scores.shape)
print(attn_weights.shape)
print(inputs.shape)
print(all_context_vecs)


torch.Size([6, 6])
torch.Size([6, 6])
torch.Size([6, 3])
tensor([[0.4447, 0.5933, 0.5694],
        [0.4438, 0.6521, 0.5576],
        [0.4450, 0.6502, 0.5562],
        [0.4320, 0.6289, 0.5297],
        [0.4675, 0.5910, 0.5120],
        [0.4194, 0.6509, 0.5517]])


In [9]:
print("Previous 2nd context vector:", context_vec_2)
print("  Matrix 2nd context vector:", all_context_vecs[1])

Previous 2nd context vector: tensor([0.4438, 0.6521, 0.5576])
  Matrix 2nd context vector: tensor([0.4438, 0.6521, 0.5576])


# Self-Attention

In [10]:
inputs = torch.tensor(
    [[0.43, 0.15, 0.89],
     [0.55, 0.87, 0.66],
     [0.57, 0.85, 0.64],
     [0.22, 0.58, 0.22],
     [0.77, 0.25, 0.10],
     [0.05, 0.80, 0.55]]
)

x_2 = inputs[1]
d_in = inputs.shape[1]
d_out = 2

torch.manual_seed(123)
W_query = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_key   = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_value = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)

query_2 = x_2 @ W_query


queries = inputs @ W_query
keys = inputs @ W_key
values = inputs @ W_value

print("queries.shape:", queries.shape)
print("keys.shape:", keys.shape)
print("values.shape:", values.shape)


keys_2 = keys[1]
attn_scores_22 = query_2.dot(keys_2)

attn_scores_2 = query_2 @ keys.T

print(attn_scores_22)
print(attn_scores_2)

d_k = keys.shape[-1]
attn_weights_2 = torch.softmax(attn_scores_2 / d_k**0.5, dim=-1)
print(attn_weights_2)

context_vec_2 = attn_weights_2 @ values
print(context_vec_2)

queries.shape: torch.Size([6, 2])
keys.shape: torch.Size([6, 2])
values.shape: torch.Size([6, 2])
tensor(1.8524)
tensor([1.2705, 1.8524, 1.8111, 0.9546, 0.5577, 1.5440])
tensor([0.1517, 0.2289, 0.2223, 0.1213, 0.0916, 0.1841])
tensor([0.3053, 0.8130])


In [11]:
import torch.nn as nn

class SelfAttention_v1(nn.Module):
    def __init__(self, d_in, d_out):
        super().__init__()
        self.W_query = nn.Parameter(torch.rand(d_in, d_out))
        self.W_key   = nn.Parameter(torch.rand(d_in, d_out))
        self.W_value = nn.Parameter(torch.rand(d_in, d_out))

    def forward(self, x):
        keys = x @ W_query
        queries = x @ W_query
        values = x @ W_value
        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(
            attn_scores / keys.shape[-1]**0.5, dim=-1
        )
        context_vec = attn_weights @ values
        
        return context_vec

In [12]:
inputs = torch.tensor(
    [[0.43, 0.15, 0.89],
     [0.55, 0.87, 0.66],
     [0.57, 0.85, 0.64],
     [0.22, 0.58, 0.22],
     [0.77, 0.25, 0.10],
     [0.05, 0.80, 0.55]]
)

torch.manual_seed(123)
sa_v1 = SelfAttention_v1(d_in, d_out)
print(sa_v1(inputs))

tensor([[0.2987, 0.8009],
        [0.3060, 0.8200],
        [0.3057, 0.8190],
        [0.2916, 0.7809],
        [0.2911, 0.7791],
        [0.2981, 0.7990]])


In [13]:
import torch.nn as nn

class SelfAttention_v2(nn.Module):
    def __init__(self, d_in, d_out, qkv_bias=False):
        super().__init__()
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)

    def forward(self, x):
        keys = x @ W_key
        queries = x @ W_query
        values = x @ W_key
        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(
            attn_scores / keys.shape[-1]**0.5, dim=-1
        )
        context_vec = attn_weights @ values

        return context_vec

In [14]:
torch.manual_seed(123)
sa_v2 = SelfAttention_v2(d_in, d_out)
print(sa_v2(inputs))

tensor([[0.3489, 0.8840],
        [0.3561, 0.9053],
        [0.3558, 0.9043],
        [0.3420, 0.8630],
        [0.3416, 0.8617],
        [0.3483, 0.8822]])


# Causal Attention

In [15]:
inputs = torch.tensor(
    [[0.43, 0.15, 0.89],
     [0.55, 0.87, 0.66],
     [0.57, 0.85, 0.64],
     [0.22, 0.58, 0.22],
     [0.77, 0.25, 0.10],
     [0.05, 0.80, 0.55]]
)

queries = sa_v2.W_query(inputs)
keys = sa_v2.W_key(inputs)
attn_scores = queries @ keys.T
attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.2, dim=-1)
print(attn_weights)

tensor([[0.1733, 0.1790, 0.1788, 0.1503, 0.1622, 0.1564],
        [0.1631, 0.1771, 0.1767, 0.1586, 0.1593, 0.1651],
        [0.1633, 0.1771, 0.1767, 0.1585, 0.1594, 0.1650],
        [0.1621, 0.1702, 0.1699, 0.1661, 0.1628, 0.1688],
        [0.1670, 0.1738, 0.1736, 0.1594, 0.1627, 0.1635],
        [0.1615, 0.1719, 0.1716, 0.1648, 0.1616, 0.1686]],
       grad_fn=<SoftmaxBackward0>)


In [16]:
context_length = attn_scores.shape[0]
mask_simple = torch.tril(torch.ones(context_length, context_length))
print(mask_simple)

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])


In [17]:
masked_simple = mask_simple * attn_weights
print(masked_simple)

row_sum = masked_simple.sum(dim=-1, keepdim=True)
print(row_sum)

masked_simple_norm = masked_simple / row_sum
print(masked_simple_norm)

tensor([[0.1733, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1631, 0.1771, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1633, 0.1771, 0.1767, 0.0000, 0.0000, 0.0000],
        [0.1621, 0.1702, 0.1699, 0.1661, 0.0000, 0.0000],
        [0.1670, 0.1738, 0.1736, 0.1594, 0.1627, 0.0000],
        [0.1615, 0.1719, 0.1716, 0.1648, 0.1616, 0.1686]],
       grad_fn=<MulBackward0>)
tensor([[0.1733],
        [0.3403],
        [0.5171],
        [0.6684],
        [0.8365],
        [1.0000]], grad_fn=<SumBackward1>)
tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4794, 0.5206, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3157, 0.3425, 0.3418, 0.0000, 0.0000, 0.0000],
        [0.2426, 0.2546, 0.2543, 0.2486, 0.0000, 0.0000],
        [0.1996, 0.2077, 0.2075, 0.1906, 0.1946, 0.0000],
        [0.1615, 0.1719, 0.1716, 0.1648, 0.1616, 0.1686]],
       grad_fn=<DivBackward0>)


In [18]:
class CausalAttention(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, qkv_bias=False):
        super().__init__()
        self.d_out = d_out
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.dropout = nn.Dropout(dropout)
        self.register_buffer(
            'mask',
            torch.triu(torch.ones(context_length, context_length), diagonal=1)
        )

    def forward(self, x):
        b, num_tokens, d_in = x.shape
        keys    = self.W_key(x)
        queries = self.W_query(x)
        values  = self.W_value(x)

        attn_scores = queries @ keys.transpose(1, 2)
        attn_scores.masked_fill_(
            self.mask.bool()[:num_tokens, :num_tokens], -torch.inf)
        attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)
        attn_weights = self.dropout(attn_weights)

        context_vec = attn_weights @ values
        return context_vec

In [19]:
batch = torch.stack((inputs, inputs), dim=0)
print(batch.shape)

torch.manual_seed(123)
context_length = batch.shape[1]
ca = CausalAttention(d_in, d_out, context_length, 0.0)
context_vecs = ca(batch)
print("context_vecs.shape:", context_vecs.shape)


torch.Size([2, 6, 3])
context_vecs.shape: torch.Size([2, 6, 2])


# Multi-head Attention

In [20]:
import torch.nn as nn

class MultiHeadAttensionWrapper(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout,
                num_heads, qkv_bias=False):
        super().__init__()
        self.heads = nn.ModuleList(
            [CausalAttention(
                d_in, d_out, context_length, dropout, qkv_bias
            ) for _ in range(num_heads) 
            ]
        )

    def forward(self, x):
        return torch.cat([head(x) for head in self.heads], dim=-1)

In [21]:
torch.manual_seed(123)
context_length = batch.shape[1]
d_in, d_out = 3, 2

mha = MultiHeadAttensionWrapper(
    d_in, d_out, context_length, 0.0, num_heads=2
)
context_vecs = mha(batch)

print(context_vecs)
print("context_vec.shape: ", context_vecs.shape)

tensor([[[-0.4519,  0.2216,  0.4772,  0.1063],
         [-0.5874,  0.0058,  0.5891,  0.3257],
         [-0.6300, -0.0632,  0.6202,  0.3860],
         [-0.5611, -0.0947,  0.5395,  0.3594],
         [-0.5483, -0.1060,  0.5263,  0.3444],
         [-0.5261, -0.1149,  0.5021,  0.3506]],

        [[-0.4519,  0.2216,  0.4772,  0.1063],
         [-0.5874,  0.0058,  0.5891,  0.3257],
         [-0.6300, -0.0632,  0.6202,  0.3860],
         [-0.5611, -0.0947,  0.5395,  0.3594],
         [-0.5483, -0.1060,  0.5263,  0.3444],
         [-0.5261, -0.1149,  0.5021,  0.3506]]], grad_fn=<CatBackward0>)
context_vec.shape:  torch.Size([2, 6, 4])


In [ ]:
class MultiHeadAttention(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, num_heads, qkv_bias=False):
        super().__init__()
        assert(d_out % num_heads ==0), "d_out must be divisible by num_heads"

        self.d_out = d_out
        self.num_heads = num_heads
        self.head_dim = d_out // num_heads
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key = nn.Linear(d_in, d_out, bias = qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.out_proj = nn.Linear(d_out, d_out)
        self.dropout = nn.Dropout(dropout)
        self.register_buffer(
            "mask",
            torch.triu(torch.ones(context_length, context_length), diagonal=1)
        )

    def forward(self, x):
        b, num_tokens, d_in = x.shape

        # b, num_tokens, d_out
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)
        print(values.shape)

        # b, num_tokens, num_heads, head_dim
        keys = keys.view(b, num_tokens, self.num_heads, self.head_dim)
        queries = queries.view(b, num_tokens, self.num_heads, self.head_dim)
        values = values.view(b, num_tokens, self.num_heads, self.head_dim)
        print(values.shape)

        # b, num_heads, num_tokens, head_dim 
        keys = keys.transpose(1,2)
        queries = queries.transpose(1,2)
        values = values.transpose(1,2)
        print(values.shape)

        # b, num_heads, num_tokens, num_tokens
        attn_scores = queries @ keys.transpose(2, 3)
        mask_bool = self.mask.bool()[:num_tokens, :num_tokens]

        attn_scores.masked_fill_(mask_bool, -torch.inf)

        attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)
        attn_weights = self.dropout(attn_weights)
        print(attn_weights.shape)

        # b, num_heads, num_tokens, head_dim
        context_vec = (attn_weights @ values)
        print(context_vec.shape)
        # b, num_tokens, num_heads, head_dim
        context_vec = context_vec.transpose(1, 2)
        print(context_vec.shape)

        context_vec = context_vec.contiguous().view(b, num_tokens, self.d_out)
        context_vec = self.out_proj(context_vec)

        return context_vec


In [30]:
torch.manual_seed(123)
context_length = batch.shape[1]
d_in, d_out = 3, 6
print(batch.shape)

mha = MultiHeadAttention(
    d_in, d_out, context_length, 0.0, num_heads=3
)
context_vecs = mha(batch)

print(context_vecs)
print("context_vec.shape: ", context_vecs.shape)

torch.Size([2, 6, 3])
torch.Size([2, 6, 6])
torch.Size([2, 6, 3, 2])
torch.Size([2, 3, 6, 2])
torch.Size([2, 3, 6, 6])
torch.Size([2, 3, 6, 2])
torch.Size([2, 6, 3, 2])
tensor([[[-2.3480e-01,  8.5975e-02,  4.3569e-01,  5.1699e-01, -1.9455e-01,
           4.2527e-01],
         [-3.0141e-01,  5.4836e-06,  4.0681e-01,  5.7115e-01, -1.4902e-01,
           4.0512e-01],
         [-3.2458e-01, -2.7917e-02,  3.9848e-01,  5.8884e-01, -1.3275e-01,
           3.9865e-01],
         [-3.3791e-01,  2.8541e-03,  3.4940e-01,  5.5472e-01, -1.2682e-01,
           3.4563e-01],
         [-3.3863e-01,  3.3878e-02,  3.4887e-01,  5.3752e-01, -1.2220e-01,
           3.3680e-01],
         [-3.4423e-01,  2.8452e-02,  3.2905e-01,  5.3252e-01, -1.2257e-01,
           3.1992e-01]],

        [[-2.3480e-01,  8.5975e-02,  4.3569e-01,  5.1699e-01, -1.9455e-01,
           4.2527e-01],
         [-3.0141e-01,  5.4836e-06,  4.0681e-01,  5.7115e-01, -1.4902e-01,
           4.0512e-01],
         [-3.2458e-01, -2.7917e-02,  